// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr9cgAn4ACFiRArfAyi2HAYqPf622RO7U',
    appId: '1:809315174438:web:69262fadbc8bbd9b157ee7',
    messagingSenderId: '809315174438',
    projectId: 'taski-manage-tasks-app',
    authDomain: 'taski-manage-tasks-app.firebaseapp.com',
    storageBucket: 'taski-manage-tasks-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgRfZzzgEm04Maxouu8foaKRVYr73T4Og',
    appId: '1:809315174438:android:f6258e17fc65893a157ee7',
    messagingSenderId: '809315174438',
    projectId: 'taski-manage-tasks-app',
    storageBucket: 'taski-manage-tasks-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdbPN9tJgjEtHAMTzsY3PXKqWFDThPCUI',
    appId: '1:809315174438:ios:ff5bbf22bb701a90157ee7',
    messagingSenderId: '809315174438',
    projectId: 'taski-manage-tasks-app',
    storageBucket: 'taski-manage-tasks-app.appspot.com',
    iosClientId: '809315174438-hq1du78db6kamp356frcp74g35cdu1fp.apps.googleusercontent.com',
    iosBundleId: 'com.biton.manage.manage',
  );
}
